a,b,c = map(int, input().split())
i = abs(a - b)+abs(b - c)
i2= abs(a - c)+abs(b - c)
j = abs(a - b)+abs(a - c)
j2= abs(c - b)+abs(a - c)
k = abs(a - c)+abs(b - a)
k2= abs(c - b)+abs(b - a)
n = min(i,i2,j,j2,k,k2)
print(n)
